swarm-control:
  hosts:
    control-md-tst-3:

swarm-worker:
  hosts:
    worker-md-tst-4:
    worker-sm-tst-5:
    worker-sm-tst-6:

swarm:
  children:
    swarm-worker:
    swarm-control:

update:
  children:
    swarm: